build:
  image: node:4.2.1
  privileged: true
  commands:
    - npm i
    - npm run build
  when:
    event: tag
cache:
  mount:
    - .git
publish:
  docker:
    when:
      event: tag
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/rancher-cli
    tag:
      - latest
      - $$TAG
