build:
  image: node:4.2.1
  environment:
    NPM_CONFIG_LOGLEVEL: warn
  commands:
    - npm i
    - npm run build
publish:
  docker:
    username: ndelitski
    password: $$DOCKER_PASSWORD
    email: ndelitski@gmail.com
    repo: ndelitski/rancher-cli
    environment:
      NPM_CONFIG_LOGLEVEL: warn
    tag:
      - latest
      - $$TAG
    when:
      event: tag
  npm:
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: $$NPM_EMAIL
    when:
      event: tag
cache:
  mount:
    - node_modules
    - .git
